using Dodostays.Api.Contracts.Payments;
using Dodostays.Api.Modules.Payments.Domain;
using Dodostays.Api.Modules.Payments.Processing;
using Microsoft.Extensions.Options;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Dodostays.Api.Modules.Payments.Invoices;

public sealed class QuestPdfInvoiceGenerator : IInvoiceGenerator
{
    private readonly IInvoiceSequenceService _sequenceService;
    private readonly IInvoicePdfStorage _storage;
    private readonly PaymentOptions _paymentOptions;
    private readonly ILogger<QuestPdfInvoiceGenerator> _logger;

    private const decimal VatRate = 0.15m; // Mauritius standard VAT rate

    public QuestPdfInvoiceGenerator(
        IInvoiceSequenceService sequenceService,
        IInvoicePdfStorage storage,
        IOptions<PaymentOptions> paymentOptions,
        ILogger<QuestPdfInvoiceGenerator> logger)
    {
        _sequenceService = sequenceService;
        _storage = storage;
        _paymentOptions = paymentOptions.Value;
        _logger = logger;
    }

    public async Task<Invoice> GenerateGuestStayAsync(GuestInvoiceInput input, CancellationToken ct)
    {
        var invoiceNumber = await _sequenceService.NextNumberAsync(InvoiceKind.GuestStay, ct);
        var issueDate = DateTimeOffset.UtcNow;

        // Calculate totals
        var nightsTotal = input.Nights * input.NightlyRateNetMur;
        var cleaningTotal = input.CleaningFeeNetMur;
        var netTotal = nightsTotal + cleaningTotal;
        var vat = netTotal * VatRate;
        var grossTotal = netTotal + vat;

        // Generate PDF
        var pdfBytes = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Element(c => ComposeGuestInvoiceHeader(c, invoiceNumber, issueDate));
                page.Content().Element(c => ComposeGuestInvoiceContent(
                    c,
                    input,
                    nightsTotal,
                    cleaningTotal,
                    netTotal,
                    vat,
                    grossTotal));
                page.Footer().AlignCenter().Text("Generated by DodoStays. Contact support@dodostays.com for queries.")
                    .FontSize(8).FontColor(Colors.Grey.Medium);
            });
        }).GeneratePdf();

        // Store PDF
        var storagePath = await _storage.StoreAsync(invoiceNumber, pdfBytes, ct);

        _logger.LogInformation("Generated guest stay invoice {InvoiceNumber} for booking {BookingId}",
            invoiceNumber, input.BookingId);

        return new Invoice
        {
            Id = Guid.NewGuid(),
            Number = invoiceNumber,
            Kind = InvoiceKind.GuestStay,
            BookingId = input.BookingId,
            PayoutId = null,
            IssuedToDisplayName = input.GuestDisplayName,
            IssuedToVatNumber = input.GuestVatNumber,
            GrossMur = grossTotal,
            VatMur = vat,
            NetMur = netTotal,
            PdfStoragePath = storagePath,
            IssuedAt = issueDate
        };
    }

    public async Task<Invoice> GenerateHostCommissionAsync(HostCommissionInvoiceInput input, CancellationToken ct)
    {
        var invoiceNumber = await _sequenceService.NextNumberAsync(InvoiceKind.HostCommission, ct);
        var issueDate = DateTimeOffset.UtcNow;

        // Calculate totals
        var netTotal = input.CommissionNetMur;
        var vat = netTotal * VatRate;
        var grossTotal = netTotal + vat;

        // Generate PDF
        var pdfBytes = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Element(c => ComposeCommissionInvoiceHeader(c, invoiceNumber, issueDate));
                page.Content().Element(c => ComposeCommissionInvoiceContent(
                    c,
                    input,
                    netTotal,
                    vat,
                    grossTotal));
                page.Footer().AlignCenter().Text("Generated by DodoStays. Contact support@dodostays.com for queries.")
                    .FontSize(8).FontColor(Colors.Grey.Medium);
            });
        }).GeneratePdf();

        // Store PDF
        var storagePath = await _storage.StoreAsync(invoiceNumber, pdfBytes, ct);

        _logger.LogInformation("Generated host commission invoice {InvoiceNumber} for payout {PayoutId}",
            invoiceNumber, input.PayoutId);

        return new Invoice
        {
            Id = Guid.NewGuid(),
            Number = invoiceNumber,
            Kind = InvoiceKind.HostCommission,
            BookingId = input.BookingId,
            PayoutId = input.PayoutId,
            IssuedToDisplayName = input.HostDisplayName,
            IssuedToVatNumber = input.HostVatNumber,
            GrossMur = grossTotal,
            VatMur = vat,
            NetMur = netTotal,
            PdfStoragePath = storagePath,
            IssuedAt = issueDate
        };
    }

    private void ComposeGuestInvoiceHeader(IContainer container, string invoiceNumber, DateTimeOffset issueDate)
    {
        container.Column(column =>
        {
            column.Spacing(10);

            // Title row with INVOICE and metadata
            column.Item().Row(row =>
            {
                row.RelativeItem().AlignLeft().Text("INVOICE")
                    .FontSize(24)
                    .Bold()
                    .LetterSpacing(1.5f)
                    .FontColor("#FF9F6A");

                row.RelativeItem().AlignRight().Column(col =>
                {
                    col.Item().Text($"Invoice #: {invoiceNumber}").FontSize(9);
                    col.Item().Text($"Issue Date: {issueDate:yyyy-MM-dd}").FontSize(9);
                    col.Item().Text($"Due Date: {issueDate:yyyy-MM-dd}").FontSize(9);
                });
            });

            column.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
        });
    }

    private void ComposeCommissionInvoiceHeader(IContainer container, string invoiceNumber, DateTimeOffset issueDate)
    {
        container.Column(column =>
        {
            column.Spacing(10);

            // Title row with INVOICE and metadata
            column.Item().Row(row =>
            {
                row.RelativeItem().AlignLeft().Text("INVOICE")
                    .FontSize(24)
                    .Bold()
                    .LetterSpacing(1.5f)
                    .FontColor("#FF9F6A");

                row.RelativeItem().AlignRight().Column(col =>
                {
                    col.Item().Text($"Invoice #: {invoiceNumber}").FontSize(9);
                    col.Item().Text($"Issue Date: {issueDate:yyyy-MM-dd}").FontSize(9);
                    col.Item().Text($"Due Date: {issueDate:yyyy-MM-dd}").FontSize(9);
                });
            });

            column.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
        });
    }

    private void ComposeGuestInvoiceContent(
        IContainer container,
        GuestInvoiceInput input,
        decimal nightsTotal,
        decimal cleaningTotal,
        decimal netTotal,
        decimal vat,
        decimal grossTotal)
    {
        container.PaddingVertical(20).Column(column =>
        {
            column.Spacing(15);

            // Merchant and Bill-To blocks
            column.Item().Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text("From:").FontSize(9).Bold().FontColor(Colors.Grey.Medium);
                    col.Item().Text(_paymentOptions.MerchantOfRecord).FontSize(10).Bold();
                    col.Item().Text(_paymentOptions.MerchantAddress).FontSize(9);
                    if (!string.IsNullOrWhiteSpace(_paymentOptions.MerchantVatNumber))
                        col.Item().Text($"VAT: {_paymentOptions.MerchantVatNumber}").FontSize(9);
                });

                row.RelativeItem().Column(col =>
                {
                    col.Item().AlignRight().Text("Bill To:").FontSize(9).Bold().FontColor(Colors.Grey.Medium);
                    col.Item().AlignRight().Text(input.GuestDisplayName).FontSize(10).Bold();
                    if (!string.IsNullOrWhiteSpace(input.GuestVatNumber))
                        col.Item().AlignRight().Text($"VAT: {input.GuestVatNumber}").FontSize(9);
                });
            });

            // Trip details
            column.Item().PaddingTop(10).Column(col =>
            {
                col.Item().Text("Trip Details:").FontSize(9).Bold().FontColor(Colors.Grey.Medium);
                col.Item().Text($"{input.ListingTitle} — {input.CheckIn:yyyy-MM-dd} to {input.CheckOut:yyyy-MM-dd} ({input.Nights} nights)")
                    .FontSize(10);
            });

            // Line items table
            column.Item().PaddingTop(10).Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(3); // Description
                    columns.ConstantColumn(60); // Qty
                    columns.ConstantColumn(80); // Unit Net
                    columns.ConstantColumn(80); // Net Total
                });

                // Header
                table.Header(header =>
                {
                    header.Cell().Element(CellStyle).Text("Description").Bold();
                    header.Cell().Element(CellStyle).AlignRight().Text("Qty").Bold();
                    header.Cell().Element(CellStyle).AlignRight().Text("Unit Net").Bold();
                    header.Cell().Element(CellStyle).AlignRight().Text("Net Total").Bold();

                    static IContainer CellStyle(IContainer c) => c.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingBottom(5);
                });

                // Accommodation line
                table.Cell().Element(CellStyle).Text($"{input.ListingTitle} — {input.Nights} nights @ MUR {input.NightlyRateNetMur:N2} net");
                table.Cell().Element(CellStyle).AlignRight().Text(input.Nights.ToString());
                table.Cell().Element(CellStyle).AlignRight().Text($"MUR {input.NightlyRateNetMur:N2}");
                table.Cell().Element(CellStyle).AlignRight().Text($"MUR {nightsTotal:N2}");

                // Cleaning fee line (if any)
                if (input.CleaningFeeNetMur > 0)
                {
                    table.Cell().Element(CellStyle).Text("Cleaning fee");
                    table.Cell().Element(CellStyle).AlignRight().Text("1");
                    table.Cell().Element(CellStyle).AlignRight().Text($"MUR {input.CleaningFeeNetMur:N2}");
                    table.Cell().Element(CellStyle).AlignRight().Text($"MUR {cleaningTotal:N2}");
                }

                static IContainer CellStyle(IContainer c) => c.PaddingVertical(5);
            });

            // Totals section
            column.Item().PaddingTop(15).AlignRight().Column(col =>
            {
                col.Item().Row(row =>
                {
                    row.ConstantItem(120).Text("Sub-total (net):").FontSize(9);
                    row.ConstantItem(100).AlignRight().Text($"MUR {netTotal:N2}").FontSize(9);
                });
                col.Item().Row(row =>
                {
                    row.ConstantItem(120).Text("VAT 15%:").FontSize(9);
                    row.ConstantItem(100).AlignRight().Text($"MUR {vat:N2}").FontSize(9);
                });
                col.Item().PaddingTop(5).BorderTop(1).BorderColor(Colors.Grey.Lighten2);
                col.Item().PaddingTop(5).Row(row =>
                {
                    row.ConstantItem(120).Text("Total:").FontSize(11).Bold();
                    row.ConstantItem(100).AlignRight().Text($"MUR {grossTotal:N2}").FontSize(11).Bold();
                });
            });

            // Damage deposit (if any) — shown separately, not included in VAT/total
            if (input.DamageDepositMur > 0)
            {
                column.Item().PaddingTop(20).AlignRight().Column(col =>
                {
                    col.Item().BorderTop(1).BorderColor(Colors.Grey.Lighten3).PaddingTop(10);
                    col.Item().Row(row =>
                    {
                        row.ConstantItem(220).Text("Damage deposit (held — refundable):").FontSize(9).Italic();
                        row.ConstantItem(100).AlignRight().Text($"MUR {input.DamageDepositMur:N2}").FontSize(9).Italic();
                    });
                });
            }
        });
    }

    private void ComposeCommissionInvoiceContent(
        IContainer container,
        HostCommissionInvoiceInput input,
        decimal netTotal,
        decimal vat,
        decimal grossTotal)
    {
        container.PaddingVertical(20).Column(column =>
        {
            column.Spacing(15);

            // Merchant and Bill-To blocks
            column.Item().Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text("From:").FontSize(9).Bold().FontColor(Colors.Grey.Medium);
                    col.Item().Text(_paymentOptions.MerchantOfRecord).FontSize(10).Bold();
                    col.Item().Text(_paymentOptions.MerchantAddress).FontSize(9);
                    if (!string.IsNullOrWhiteSpace(_paymentOptions.MerchantVatNumber))
                        col.Item().Text($"VAT: {_paymentOptions.MerchantVatNumber}").FontSize(9);
                });

                row.RelativeItem().Column(col =>
                {
                    col.Item().AlignRight().Text("Bill To:").FontSize(9).Bold().FontColor(Colors.Grey.Medium);
                    col.Item().AlignRight().Text(input.HostDisplayName).FontSize(10).Bold();
                    if (!string.IsNullOrWhiteSpace(input.HostVatNumber))
                        col.Item().AlignRight().Text($"VAT: {input.HostVatNumber}").FontSize(9);
                });
            });

            // Commission details
            column.Item().PaddingTop(10).Column(col =>
            {
                col.Item().Text("Commission:").FontSize(9).Bold().FontColor(Colors.Grey.Medium);
                col.Item().Text($"Platform commission — {input.ListingTitle}").FontSize(10);
            });

            // Line items table
            column.Item().PaddingTop(10).Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(3); // Description
                    columns.ConstantColumn(60); // Qty
                    columns.ConstantColumn(80); // Unit Net
                    columns.ConstantColumn(80); // Net Total
                });

                // Header
                table.Header(header =>
                {
                    header.Cell().Element(CellStyle).Text("Description").Bold();
                    header.Cell().Element(CellStyle).AlignRight().Text("Qty").Bold();
                    header.Cell().Element(CellStyle).AlignRight().Text("Unit Net").Bold();
                    header.Cell().Element(CellStyle).AlignRight().Text("Net Total").Bold();

                    static IContainer CellStyle(IContainer c) => c.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingBottom(5);
                });

                // Commission line
                table.Cell().Element(CellStyle).Text($"Platform commission — {input.ListingTitle}");
                table.Cell().Element(CellStyle).AlignRight().Text("1");
                table.Cell().Element(CellStyle).AlignRight().Text($"MUR {input.CommissionNetMur:N2}");
                table.Cell().Element(CellStyle).AlignRight().Text($"MUR {netTotal:N2}");

                static IContainer CellStyle(IContainer c) => c.PaddingVertical(5);
            });

            // Totals section
            column.Item().PaddingTop(15).AlignRight().Column(col =>
            {
                col.Item().Row(row =>
                {
                    row.ConstantItem(120).Text("Sub-total (net):").FontSize(9);
                    row.ConstantItem(100).AlignRight().Text($"MUR {netTotal:N2}").FontSize(9);
                });
                col.Item().Row(row =>
                {
                    row.ConstantItem(120).Text("VAT 15%:").FontSize(9);
                    row.ConstantItem(100).AlignRight().Text($"MUR {vat:N2}").FontSize(9);
                });
                col.Item().PaddingTop(5).BorderTop(1).BorderColor(Colors.Grey.Lighten2);
                col.Item().PaddingTop(5).Row(row =>
                {
                    row.ConstantItem(120).Text("Total:").FontSize(11).Bold();
                    row.ConstantItem(100).AlignRight().Text($"MUR {grossTotal:N2}").FontSize(11).Bold();
                });
            });
        });
    }
}
